name: Assign Reviewer

on:
  pull_request:
    types: [opened, edited]

permissions:
  issues: write 

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Detect PR Type
        id: detect
        run: |
          # 通过PR正文内容判断类型
          if grep -q "## 友链申请信息" <<< "${{ github.event.pull_request.body }}"; then
            echo "pr_type=friend-link" >> $GITHUB_ENV
          elif grep -q "## 问题描述" <<< "${{ github.event.pull_request.body }}"; then
            echo "pr_type=code-change" >> $GITHUB_ENV
          fi

      - name: Assign for Friend Link
        if: env.pr_type == 'friend-link'
        uses: peter-evans/assignee@v2
        with:
          assignees: China-fan
          add-assignees: true

      - name: Assign for Code Change
        if: env.pr_type == 'code-change'
        uses: peter-evans/assignee@v2
        with:
          assignees: zhao2022-Ux
          add-assignees: true