name: autofix.ci
on:
  pull_request:
  push:
    branches: [ "master" ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: pip install pre-commit
      - run: pre-commit install
      - run: pre-commit sample-config > .pre-commit-config.yaml
      - run: pre-commit run --files /link.js

      - uses: autofix-ci/action@551dded8c6cc8a1054039c8bc0b8b48c51dfc6ef
